= London (May 26th) Drools & jBPM community contributor meeting
:page-interpolate: true
:awestruct-author: mdproctor
:awestruct-layout: blogPostBase
:awestruct-tags: [Drools, jBPM]

London, Chiswick, May 26th to May 30th

During next week a large percentage of the Drools team, some of the jBPM team and some community members will be meeting in London (Chiswick). There won’t be any presentations, we’ll just be in a room hacking, designing, exchanging ideas and planing. This is open to community members who wish to contribute towards Drools or jBPM, and want help with those contributions. This also includes people working on open source or academic projects that utilise Drools or jBPM. Email me if you want to attend, our locations may very (but within chiswick) each day. 

We will not be able to make the day time available to people looking for general Drools or jBPM guidance (unless you want to buy us all lunch). But we will be organising evenings things (like bowling) and could make wed or thu evening open to people wanting general chats and advice. Email me if you’re interested, and after discussing with the team, I’ll let you know.

Those currently attending:

* Mark Proctor (mon-fri) Group architect
* Edson Tirelli (mon-fri) Drools backend, and project lead
* Mario Fusco (mon-fri) Drools backend
* Davide Sottara (wed-fri) Drools backend
* Alex Porcelli (mon-fri) Drools UI
* Michael Anstis (thu-fri) Drools UI
* Kris Verlaenen (wed-thu) jBPM backend, and project lead
* Mauricio Salatino (mon-fri) jBPM tasks and general UI