= Forum (community volunteer support)
:awestruct-layout: base
:showtitle:

All our forums now use Google Groups, which allows for both web and email interaction.


Please follow these recommendations when posting a question:

* Please post to the relevant group. DO NOT post setup, configuration, adminstration questions to Drools Usage
* Before posting first search the archives for similar questions. Searches should include Google Groups, StackOverflow and Jira.
* Get to the point. Keep it as short as possible.
* Include _relevant_ technical details (version, stacktrace, short code snippet, ...).
* Be polite, friendly and clear. Reread your question before posting it.
* Be patient. Do not email people directly. This isn't link:product.html[paid support].

== Setup questions and discussions
Installation, configuration, setup and administration discussions for the Workbench, Eclipse, runtime environments and general enterprise architectures. 

* https://groups.google.com/forum/#!forum/drools-setup[Drools setup forum and mailing list].

== Usage questions and discussions
Authoring and execution with Drools. Includes all authoring metaphors from text DRL to UI scorecards. General API help and best practices in building rule based systems.

* https://groups.google.com/forum/#!forum/drools-usage[Drools usage forum and mailing list].

== StackOverflow
StackOverflow is a popular externally run question and answer site, it does not allow for general discussions, and provides scoring and moderation.

* http://stackoverflow.com/questions/tagged/drools[StackOverflow Q&A site].

== Development discussions
If you want to help improve Drools or have ideas you want to discuss (bug fixing, documentation or feature development) then come talk with us. 

* https://groups.google.com/forum/#!forum/drools-development[Drools development forum and mailing list].
* link:../code/sourceCode.html[Help Building Drools from source]
* And link:chat.html[chat with us] (recommended). Contributors will get priority real time assistance on irc.
